what is NumPy?
NumPy is the foundational Python library for numerical computing. Its central object is the homogeneous, multidimensional ndarray, which enables compact data storage and fast vectorized operations. This notebook explains the most useful functions with small, runnable examples.

In [1]:
import numpy as np
# Q1: Create a NumPy array containing numbers from 1 to 10.

arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
# Q2: Create an array containing even numbers from 2 to 20.
arr_even = np.arange(2, 21, 2)
arr_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
# Q3: Create an array of 10 zeros.
arr_zeros = np.zeros(10, dtype=int)
arr_zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Q4: Create an array of 15 ones.
arr_ones = np.ones(15, dtype=int)
arr_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
# Q5: Create a 4×4 identity matrix.
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
# Q6: Create a 3×5 array filled with the number 8.
arr = np.ones((3, 5), dtype=int) * 8
arr

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [7]:
# Q7: Create an array containing 20 equally spaced values between 5 and 50.
arr = np.linspace(5, 50, 20 ,dtype=int)
arr

array([ 5,  7,  9, 12, 14, 16, 19, 21, 23, 26, 28, 31, 33, 35, 38, 40, 42,
       45, 47, 50])

In [8]:
# Q8: Create a random 3×4 array of floating-point numbers.
arr = np.random.rand(3, 4)
arr

array([[0.30491214, 0.06235705, 0.59164279, 0.64530429],
       [0.39119059, 0.51492641, 0.49091097, 0.86677056],
       [0.05991351, 0.11938464, 0.77358378, 0.15411956]])

In [9]:
# Q9: Create a random 4×4 array of integers between 10 and 100.
arr = np.random.randint(10, 100, size = (4, 4))
arr

array([[32, 72, 41, 51],
       [14, 67, 70, 73],
       [61, 36, 28, 50],
       [70, 22, 10, 70]])

In [10]:
# Q10: Print the following properties of an array:
# Shape
# Size
# Data type
# Number of dimensions

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)



Shape: (2, 3)
Size: 6
Data type: int64
Number of dimensions: 2


In [11]:
# Q11: Reshape a 1D array containing numbers from 1 to 12 into a 3×4 matrix.
arr = np.arange(1, 13).reshape(3, 4) # This reshapes the 1D array into a 3x4 matrix
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
# Q12: Convert a 4×5 matrix into a 1D array.
arr = np.random.randint(1, 100, size=(4, 5))
arr = arr.flatten() # This flattens the 4x5 matrix into a 1D array
arr

array([68, 50, 82, 63, 67, 43, 92, 31, 59, 74, 73, 75, 90, 86,  6, 48, 68,
       87, 22, 88])

In [13]:
# Q13: Access:
# First element
# Last element
# Middle element
# of a NumPy array.
arr = np.array([1, 2, 3, 4, 5])
print("First element:", arr[0])  # First element
print("Last element:", arr[-1])  # Last element
print("Middle element:", arr[len(arr)//2])  # Middle element  

First element: 1
Last element: 5
Middle element: 3


In [14]:
# Q14: Extract the first three rows from a 5×5 matrix.
arr = np.random.randint(1, 100, size=(5, 5))
print("Original array:\n", arr)
arr1 = arr[:3, :]  # Extracting the first three rows
arr1

Original array:
 [[87  7 97 70 90]
 [52 51  1 77 86]
 [52 66 82 17 22]
 [90 46 86 99 69]
 [93 94 55 26 23]]


array([[87,  7, 97, 70, 90],
       [52, 51,  1, 77, 86],
       [52, 66, 82, 17, 22]])

In [15]:
# Q15: Extract the last two columns from a matrix.
arr = np.random.randint(1, 100, size=(3, 3))
print("Original array:\n", arr)
arr1 = arr[:, -2:]  # Extracting the last two columns
arr1

Original array:
 [[72 52 11]
 [ 8 32  9]
 [83 35 61]]


array([[52, 11],
       [32,  9],
       [35, 61]])

In [16]:
# Q16: Replace all values greater than 20 with 100.
arr = np.random.randint(1, 100, size=(3, 3))
print("Original array:\n", arr)
arr[arr > 20] = 100
print("Array after replacement:\n", arr)

Original array:
 [[88 27 22]
 [92 59 86]
 [56 26 91]]
Array after replacement:
 [[100 100 100]
 [100 100 100]
 [100 100 100]]


In [17]:
# Q17: Count the number of elements greater than 50.
arr = np.random.randint(1, 100, size=(3, 3))
print("Original array:\n", arr)
count = np.sum(arr > 50)
print("Number of elements greater than 50:", count)

Original array:
 [[77  8 39]
 [99 81 38]
 [60 34 55]]
Number of elements greater than 50: 5


In [18]:
# Q18: Create a Boolean mask for even numbers.
arr = np.random.randint(1, 100, size = (3, 3))
print("Original array:\n", arr)
mask = arr % 2 == 0
print("Boolean mask for even numbers:\n", mask)

Original array:
 [[ 4 34 60]
 [81 58 83]
 [98 89 56]]
Boolean mask for even numbers:
 [[ True  True  True]
 [False  True False]
 [ True False  True]]


In [19]:
# Q19: Print only the odd numbers from an array.
arr = np.random.randint(1, 100, size=(3, 3))
print("Original array:\n", arr)
odd_numbers = arr[arr % 2 != 0]
print("Odd numbers from the array:\n", odd_numbers)

Original array:
 [[37 35  6]
 [99 62 81]
 [76 65 24]]
Odd numbers from the array:
 [37 35 99 81 65]


In [20]:
# Q20: Reverse a NumPy array.
arr = np.random.randint(1, 100, size=(3, 3))
print("Original array:\n", arr)
reversed_arr = arr[::-1, ::-1]  # Reversing the array
print("Reversed array:\n", reversed_arr)

Original array:
 [[94 47 57]
 [64  8 50]
 [94 38 68]]
Reversed array:
 [[68 38 94]
 [50  8 64]
 [57 47 94]]
