In [2]:
import numpy as np

In [4]:
list1 = [1,2,3]

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr1.shape

(2, 3)

In [9]:
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
arr.shape


(2, 2, 3)

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]],dtype = float) #bydefault integer datatype 

arr1[:2]


array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr1[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [30]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1 = np.arange(0,101)
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
arr1 = np.linspace(0,10,5)
arr1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
arr1 = np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
arr = np.zeros((3,3),dtype = int)
np.fill_diagonal(arr,5)
arr

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [40]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,12,13,14,15])
arr1+arr2

array([11, 14, 16, 18, 20])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10])
arr1+arr2  #broadcasting 

array([11, 12, 13, 14, 15])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr1*arr2


array([[ 7, 16, 27],
       [40, 55, 72]])

In [49]:
#first row sum 
print(np.sum((arr1*arr2)[0]))

50


In [52]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
print(np.matmul(arr1,arr2))

11


In [55]:
arr1 = np.array([1,2,3,4,5,6,7,8])
# for i in arr1:
#     if i>4:
#         print(i)
arr1[arr1>4]

array([5, 6, 7, 8])

In [ ]:
arr1.shape


(8,)

In [ ]:
arr1.reshape(2,4) 
#convert 1d to 2d 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1.flatten() #again convert 1d from 2d or 3d 

array([1, 2, 3, 4, 5, 6, 7, 8])